// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZdYz-yqZYDG6jkx-zLU_6KkZzSCP3818',
    appId: '1:930063263624:web:fde6b503c5a390d1be3c3d',
    messagingSenderId: '930063263624',
    projectId: 'todo-uasmdi',
    authDomain: 'todo-uasmdi.firebaseapp.com',
    storageBucket: 'todo-uasmdi.firebasestorage.app',
    measurementId: 'G-DQTYX5229F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGcADbu98hmBqvdu043z2IGV6Mlp4nZD4',
    appId: '1:930063263624:android:91922ac40e84da1fbe3c3d',
    messagingSenderId: '930063263624',
    projectId: 'todo-uasmdi',
    storageBucket: 'todo-uasmdi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw2thB2zNuUj67NDaZeXBQ6bTAmSSOoEA',
    appId: '1:930063263624:ios:405686f87b7e769dbe3c3d',
    messagingSenderId: '930063263624',
    projectId: 'todo-uasmdi',
    storageBucket: 'todo-uasmdi.firebasestorage.app',
    iosBundleId: 'com.example.todoFizard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw2thB2zNuUj67NDaZeXBQ6bTAmSSOoEA',
    appId: '1:930063263624:ios:405686f87b7e769dbe3c3d',
    messagingSenderId: '930063263624',
    projectId: 'todo-uasmdi',
    storageBucket: 'todo-uasmdi.firebasestorage.app',
    iosBundleId: 'com.example.todoFizard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZdYz-yqZYDG6jkx-zLU_6KkZzSCP3818',
    appId: '1:930063263624:web:695dc4852524bfe7be3c3d',
    messagingSenderId: '930063263624',
    projectId: 'todo-uasmdi',
    authDomain: 'todo-uasmdi.firebaseapp.com',
    storageBucket: 'todo-uasmdi.firebasestorage.app',
    measurementId: 'G-4QZ02XNKS7',
  );
}
